---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: my-atomic-os
# description will be included in the image's metadata
description: ThinkPad T480 config 

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora-ostree-desktops/silverblue
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  
  - from-file: system.yml
  - from-file: chezmoi.yml
  - from-file: gnome-extensions.yml

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

